### ISSUE TITLE
Name conflicts with nim-lang/cairo

### ISSUE THREAD

**Issue by oderwat** [StefanSalewski/nim-cairo#1]
Just wanted to tell you that this lib conflicts with the "original" https://github.com/nim-lang/cairo from the nim-lang repository. It happens that nim-forum captchas does not compile anymore if your GTK3 wrappers are installed.

**Comment by StefanSalewski** [comment]
Sure. I tried to make my wrappers compatible with the legacy ones when possible,  but I can not avoid all conflicts. Generally I regard my wrapper "supperior".

**Comment by oderwat** [comment]
I wonder if that could be unified. It is not possible to install both with nimble :(

**Comment by StefanSalewski** [comment]
I wonder too, and I mentioned this topic in the Forum. But there was no direct answer from the developers, I think they are all very busy. My feeling is, that nimble does not support something like paths for modules. Nim itself does not support paths also, even something like ../ gave problems in the past, I mentioned that in the forum. Some said that explicit paths would be bad, but relative path should work. But they did not. I understand that this is not a high priority for developers, with 47 serious open bugs...

**Comment by oderwat** [comment]
Actually I just fixed `../module` for the compiler a day ago. But the easiest solutions (the only ones) is that you either add add all modules into one package or rename them to something like gkt3_cairo gtk3_something.. even salewski_cairo would work.

Maybe the official cairo even could get replaced with yours if it is better. I don't know what all depends on it though. But having a new version could mean not to be backwards compatible. I think nimble can handle that.
